[package]
name = "metaheuristics-nature"
description = "A collection of nature-inspired metaheuristic algorithms."
version = "0.9.0"
authors = ["KmolYuan <pyslvs@gmail.com>"]
edition = "2018"
license-file = "LICENSE"
readme = "README.md"
repository = "https://github.com/KmolYuan/metaheuristics-nature-rs"
keywords = ["metaheuristic", "algorithm", "optimization"]

[features]
parallel = []

[dependencies]
rand = "0.8"
ndarray = { version = "0.15", default-features = false }
