name: Deploy
on:
  push:
    tags: [ v* ]
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
          cargo login ${{ secrets.CRATE_IO }}
          cargo publish
